package org.acme.optaplanner.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Curriculum implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Curriculum() {
    }

    private String code;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getLabel() {
        return code;
    }

    @Override
    public String toString() {
        return code;
    }

}
