package org.acme.optaplanner.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Lecture implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Course")
   private org.acme.optaplanner.curriculumcourse.Course course;
   @org.kie.api.definition.type.Label(value = "Lecture Index In Course")
   private java.lang.Integer lectureIndexInCourse;
   @org.kie.api.definition.type.Label(value = "Period")
   private org.acme.optaplanner.curriculumcourse.Period period;
   @org.kie.api.definition.type.Label(value = "Room")
   private org.acme.optaplanner.curriculumcourse.Room room;
   @org.kie.api.definition.type.Label(value = "Id")
   private java.lang.Long id;

   public Lecture()
   {
   }

   public org.acme.optaplanner.curriculumcourse.Course getCourse()
   {
      return this.course;
   }

   public void setCourse(org.acme.optaplanner.curriculumcourse.Course course)
   {
      this.course = course;
   }

   public java.lang.Integer getLectureIndexInCourse()
   {
      return this.lectureIndexInCourse;
   }

   public void setLectureIndexInCourse(java.lang.Integer lectureIndexInCourse)
   {
      this.lectureIndexInCourse = lectureIndexInCourse;
   }

   public org.acme.optaplanner.curriculumcourse.Period getPeriod()
   {
      return this.period;
   }

   public void setPeriod(org.acme.optaplanner.curriculumcourse.Period period)
   {
      this.period = period;
   }

   public org.acme.optaplanner.curriculumcourse.Room getRoom()
   {
      return this.room;
   }

   public void setRoom(org.acme.optaplanner.curriculumcourse.Room room)
   {
      this.room = room;
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public Lecture(org.acme.optaplanner.curriculumcourse.Course course,
         java.lang.Integer lectureIndexInCourse,
         org.acme.optaplanner.curriculumcourse.Period period,
         org.acme.optaplanner.curriculumcourse.Room room, java.lang.Long id)
   {
      this.course = course;
      this.lectureIndexInCourse = lectureIndexInCourse;
      this.period = period;
      this.room = room;
      this.id = id;
   }

}
