package org.acme.optaplanner.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Period implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Period() {
    }

    private Day day;
    private Timeslot timeslot;

    public Day getDay() {
        return day;
    }

    public void setDay(Day day) {
        this.day = day;
    }

    public Timeslot getTimeslot() {
        return timeslot;
    }

    public void setTimeslot(Timeslot timeslot) {
        this.timeslot = timeslot;
    }

    public String getLabel() {
        return day.getLabel() + " " + timeslot.getLabel();
    }

    @Override
    public String toString() {
        return day + "-" + timeslot;
    }

}
