package org.acme.optaplanner.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Room implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Room() {
    }

    private String code;
    private int capacity;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public int getCapacity() {
        return capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public String getLabel() {
        return code;
    }

    @Override
    public String toString() {
        return code;
    }

}
