package org.acme.optaplaner.curriculumcourse;

import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Course implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Id")
   private java.lang.Long id;

   public Course()
   {
   }

   private String code;

   private Teacher teacher;
   private int lectureSize;
   private int minWorkingDaySize;

   private List<Curriculum> curriculumList;
   private int studentSize;

   public String getCode()
   {
      return code;
   }

   public void setCode(String code)
   {
      this.code = code;
   }

   public Teacher getTeacher()
   {
      return teacher;
   }

   public void setTeacher(Teacher teacher)
   {
      this.teacher = teacher;
   }

   public int getLectureSize()
   {
      return lectureSize;
   }

   public void setLectureSize(int lectureSize)
   {
      this.lectureSize = lectureSize;
   }

   public int getMinWorkingDaySize()
   {
      return minWorkingDaySize;
   }

   public void setMinWorkingDaySize(int minWorkingDaySize)
   {
      this.minWorkingDaySize = minWorkingDaySize;
   }

   public List<Curriculum> getCurriculumList()
   {
      return curriculumList;
   }

   public void setCurriculumList(List<Curriculum> curriculumList)
   {
      this.curriculumList = curriculumList;
   }

   public int getStudentSize()
   {
      return studentSize;
   }

   public void setStudentSize(int studentSize)
   {
      this.studentSize = studentSize;
   }

   @Override
   public String toString()
   {
      return code;
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public Course(
         java.lang.Long id,
         java.lang.String code,
         org.acme.optaplaner.curriculumcourse.Teacher teacher,
         int lectureSize,
         int minWorkingDaySize,
         java.util.List<org.acme.optaplaner.curriculumcourse.Curriculum> curriculumList,
         int studentSize)
   {
      this.id = id;
      this.code = code;
      this.teacher = teacher;
      this.lectureSize = lectureSize;
      this.minWorkingDaySize = minWorkingDaySize;
      this.curriculumList = curriculumList;
      this.studentSize = studentSize;
   }

}