package org.acme.optaplaner.curriculumcourse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Teacher implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Teacher() {
    }
    
    private String code;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getLabel() {
        return code;
    }

    @Override
    public String toString() {
        return code;
    }

}